### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by masak** [zeroeth/shiver_me_dithers#1]
Greetings, @zeroeth. In my recent explorations into CGA art, I stumbled on this repository. Nice work!

Are you open to letting others build on the work in this repository? More specifically, what license would you consider the code to be under? (In the absence of a LICENSE file, the code is simply copyrighted by default, and I have no claims to using it or modifying it.)

GitHub has created [choosealicense.com](https://choosealicense.com/) to help people choose an appropriate software license.

I'm willing to do the work and submit a PR with the LICENSE file of your choice.

**Comment by zeroeth** [comment]
Thanks for the interest, added an MIT license so hack away!

I always wanted to extend this to an interactive gui with some contrast/saturation sliders (before the dither processing). Right now its one of those 'fill a directory and prune' types.

Side note, when I was creating the file via githubs web gui, naming it 'LICENSE' automatically popped up a button for filling out a template. Sweet.
